Pass LLVMgold.so plugin to linker on DragonFly.
Turns out there was just a one small missing detail.
Now clang -flto works fine.

$ ./4th/clangb 1.c 2.c -flto && ./a.out
Labas rytas suraitytas!
$ ./4th/clangb 1.o 2.o && ./a.out
/usr/libexec/binutils227/elf/ld.gold: error: 1.o:1:3: invalid character
/usr/libexec/binutils227/elf/ld.gold: error: 1.o:1:3: syntax error, unexpected $end
/usr/libexec/binutils227/elf/ld.gold: error: 1.o: not an object or archive
/usr/libexec/binutils227/elf/ld.gold: error: 2.o:1:3: invalid character
/usr/libexec/binutils227/elf/ld.gold: error: 2.o:1:3: syntax error, unexpected $end
/usr/libexec/binutils227/elf/ld.gold: error: 2.o: not an object or archive
/usr/lib/crt1.o:crt1.c:function _start: error: undefined reference to 'main'
clangb: error: linker command failed with exit code 1 (use -v to see invocation)
$ ./4th/clangb 1.o 2.o -flto && ./a.out
Labas rytas suraitytas!